[profile.default]
src = "contracts"
test = "foundry-test"
out = "out"
libs = ["lib", "node_modules"]
via_ir = true
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@pythnetwork/=node_modules/@pythnetwork/"
]

[profile.default.optimizer_details]
yul = true
